# YAML configuration file for Docker Compose version 3.8
version: '3.8'
# Define services
services:
  # Database service using PostgreSQL image
  database:
    image: postgres:latest  
    environment:
      POSTGRES_DB: database_healing_nature 
      POSTGRES_USER: healing_nature 
      POSTGRES_PASSWORD: healing_nature_potato
    ports:
      - "5432:5432"  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL
  # Backend service
  backend:
    build: .
    ports:
      - "3333:3333"  # Forward the container's port 3333 to the host machine's port 3333 for accessing the backend service
    depends_on:
      - database  # Ensure that the backend service starts after the database service is up and running
    env_file:
      - .env  # Load environment variables from the .env file in the current directory